import { deriveDid, fromB64u } from '@web3/crypto';
import type { ModuleContext, Web3Module } from '../context.js';
import type { Role } from '../services/accounts.js';
import { requireRole } from '../services/auth.js';

/**
 * accounts — sign-up + identity. `POST /accounts/signup` mints a human address (`local@web3.0`) and a
 * one-time Web3.0 token; `GET /accounts/me` resolves the caller's account from that token; `GET /accounts`
 * (admin) lists them. This replaces the single shared WEB3_ADMIN_TOKEN with real per-user roles.
 */
export function accountsModule(): Web3Module {
  return {
    name: 'accounts',
    version: '0.1.0',
    register(ctx: ModuleContext) {
      const { http, accounts } = ctx;

      // Faucet backfill: accounts created before wallets existed never received the signup grant.
      // Mint it once to any account with NO mint in its ledger history — idempotent (an account
      // that received its grant and spent it to zero has a mint entry, so it is never re-granted).
      if (ctx.config.faucetGrant > 0) {
        const minted = new Set<string>();
        for (const e of ctx.ledger.all()) {
          if (e.type !== 'payment') continue;
          const d = e.data as { from?: string | null; to?: string };
          if (d.from === null && d.to) minted.add(d.to);
        }
        for (const acct of accounts.list()) {
          if (minted.has(acct.address)) continue;
          ctx.ledger.mint(
            acct.address as Parameters<typeof ctx.ledger.mint>[0],
            ctx.config.faucetGrant,
          );
          ctx.log.info(`faucet backfill: granted ${acct.address} its signup wallet`);
        }
      }

      http.post('/accounts/signup', async (request, reply) => {
        const body = (request.body ?? {}) as { local?: string; role?: Role; pubkey?: string };
        const local = (body.local ?? '').trim();
        const role: Role = body.role ?? 'developer';
        // The account's transaction-signing public key (base64url ML-DSA), generated by the client.
        // Optional for back-compat, but required to send/receive trustless transactions.
        const pubkey = typeof body.pubkey === 'string' ? body.pubkey.trim() : '';
        if (!local) return reply.code(400).send({ error: 'local (handle) is required' });
        if (pubkey) {
          try {
            fromB64u(pubkey); // reject a malformed key before it reaches the chain
          } catch {
            return reply.code(400).send({ error: 'pubkey must be base64url-encoded' });
          }
        }

        // The first account bootstraps as admin freely. After that, minting an admin requires admin.
        if (
          role === 'admin' &&
          accounts.hasAdmin() &&
          !requireRole(request, reply, accounts, 'admin')
        ) {
          return;
        }
        try {
          const created = await accounts.signup(local, role);
          // Bind the account's signing key on-chain so every node learns it (see AccountData). This
          // is what lets the account send/receive trustless, account-signed transactions.
          if (pubkey) {
            ctx.ledger.bindAccount(
              created.address as Parameters<typeof ctx.ledger.bindAccount>[0],
              created.role,
              pubkey,
              deriveDid(fromB64u(pubkey)),
            );
          }
          // Every account gets a personal wallet with the faucet grant — same as agents. This is
          // what operators stake from (Ethereum-deposit-contract style) to become an authority.
          if (ctx.config.faucetGrant > 0) {
            ctx.ledger.mint(
              created.address as Parameters<typeof ctx.ledger.mint>[0],
              ctx.config.faucetGrant,
            );
          }
          ctx.bus.emit({
            kind: 'account.created',
            summary: `${created.address} signed up as ${created.role}`,
          });
          // The token is returned exactly once — the client must save it now.
          return reply.code(201).send(created);
        } catch (err) {
          return reply.code(400).send({ error: err instanceof Error ? err.message : String(err) });
        }
      });

      // Bind (or rotate) the signing key for the SIGNED-IN account — how accounts created before
      // keys existed (or a fresh device) enable trustless payments. Authenticated by the caller's
      // token; the key is generated client-side and only its public half is sent.
      http.post('/accounts/key', async (request, reply) => {
        const acct = accounts.authenticate(request.headers['x-web3-token'] as string | undefined);
        if (!acct) return reply.code(401).send({ error: 'authentication required' });
        const pubkey = ((request.body ?? {}) as { pubkey?: string }).pubkey?.trim() ?? '';
        if (!pubkey) return reply.code(400).send({ error: 'pubkey is required' });
        try {
          ctx.ledger.bindAccount(
            acct.address as Parameters<typeof ctx.ledger.bindAccount>[0],
            acct.role,
            pubkey,
            deriveDid(fromB64u(pubkey)),
          );
        } catch {
          return reply.code(400).send({ error: 'pubkey must be base64url-encoded' });
        }
        return reply.send({ bound: true, address: acct.address });
      });

      http.get('/accounts/me', async (request, reply) => {
        const acct = accounts.authenticate(
          (request.headers['x-web3-token'] as string | undefined) ??
            (typeof request.headers.authorization === 'string' &&
            request.headers.authorization.startsWith('Bearer ')
              ? request.headers.authorization.slice(7)
              : undefined),
        );
        if (!acct) return reply.code(401).send({ error: 'authentication required' });
        return accounts.view(acct);
      });

      http.get('/accounts', async (request, reply) => {
        if (!requireRole(request, reply, accounts, 'admin')) return;
        return { accounts: accounts.list() };
      });
    },
  };
}
