import type { Web3Id } from '@web3/core';
import { deriveDid, fromB64u } from '@web3/crypto';
import type { LedgerEntry } from '@web3/ledger';
import type { ModuleContext, Web3Module } from '../context.js';
import type { Role } from '../services/accounts.js';
import { currentAccount, requireAuthed, requireRole } from '../services/auth.js';

/**
 * accounts — sign-up + identity. `POST /accounts/signup` mints a human address (`local@web3.0`) and a
 * one-time Web3.0 token; `GET /accounts/me` resolves the caller's account from that token; `GET /accounts`
 * (admin) lists them. This replaces the single shared WEB3_ADMIN_TOKEN with real per-user roles.
 */
export function accountsModule(): Web3Module {
  return {
    name: 'accounts',
    version: '0.1.0',
    register(ctx: ModuleContext) {
      const { http, accounts } = ctx;

      // On a PoA FOLLOWER, account registration + key binding are authority-privileged (they mint
      // faucet and write on-chain identity), so this node can't do them itself — it forwards them
      // to the authority and lets the result replicate back in a block. Returns the authority's
      // base URL when this node must forward, or undefined when it may handle writes locally
      // (solo / consensus-off / this node IS an authority).
      const authorityUrl = (): string | undefined =>
        ctx.consensus.enabled && !ctx.consensus.isAuthority()
          ? ctx.config.consensus.peers[0]?.replace(/\/$/, '')
          : undefined;
      const passHeaders = (request: { headers: Record<string, unknown> }): Record<
        string,
        string
      > => {
        const h: Record<string, string> = { 'content-type': 'application/json' };
        const t = request.headers['x-web3-token'];
        if (typeof t === 'string') h['x-web3-token'] = t;
        const a = request.headers['x-admin-token'];
        if (typeof a === 'string') h['x-admin-token'] = a;
        return h;
      };

      // Faucet backfill: accounts created before wallets existed never received the signup grant.
      // Mint it once to any account with NO mint in its ledger history — idempotent (an account
      // that received its grant and spent it to zero has a mint entry, so it is never re-granted).
      // Authorities only: a follower must never mint (its faucet arrives via block replication).
      if (ctx.consensus.isAuthority() && ctx.config.faucetGrant > 0) {
        const minted = new Set<string>();
        for (const e of ctx.ledger.all()) {
          if (e.type !== 'payment') continue;
          const d = e.data as { from?: string | null; to?: string };
          if (d.from === null && d.to) minted.add(d.to);
        }
        for (const acct of accounts.list()) {
          if (minted.has(acct.address)) continue;
          ctx.ledger.mint(
            acct.address as Parameters<typeof ctx.ledger.mint>[0],
            ctx.config.faucetGrant,
          );
          ctx.log.info(`faucet backfill: granted ${acct.address} its signup wallet`);
        }
      }

      http.post('/accounts/signup', async (request, reply) => {
        const body = (request.body ?? {}) as { local?: string; role?: Role; pubkey?: string };
        const local = (body.local ?? '').trim();
        const role: Role = body.role ?? 'developer';
        // The account's transaction-signing public key (base64url ML-DSA), generated by the client.
        // Optional for back-compat, but required to send/receive trustless transactions.
        const pubkey = typeof body.pubkey === 'string' ? body.pubkey.trim() : '';
        if (!local) return reply.code(400).send({ error: 'local (handle) is required' });
        if (pubkey) {
          try {
            fromB64u(pubkey); // reject a malformed key before it reaches the chain
          } catch {
            return reply.code(400).send({ error: 'pubkey must be base64url-encoded' });
          }
        }

        // Follower: forward the signup to the authority (which mints + binds on-chain), then mirror
        // the returned account locally so its token still authenticates here. The wallet + key
        // binding arrive via block replication.
        const upstream = authorityUrl();
        if (upstream) {
          try {
            const res = await fetch(`${upstream}/accounts/signup`, {
              method: 'POST',
              headers: passHeaders(request),
              body: JSON.stringify({ local, role, pubkey: pubkey || undefined }),
            });
            const data = (await res.json().catch(() => ({}))) as {
              address?: string;
              role?: Role;
              token?: string;
            };
            if (res.ok && data.address && data.role && data.token) {
              await accounts.adopt(data.address, data.role, data.token);
            }
            return reply.code(res.status).send(data);
          } catch {
            return reply.code(502).send({ error: 'could not reach an authority to register' });
          }
        }

        // The first account bootstraps as admin freely. After that, minting an admin requires admin.
        if (
          role === 'admin' &&
          accounts.hasAdmin() &&
          !requireRole(request, reply, accounts, 'admin')
        ) {
          return;
        }
        try {
          const created = await accounts.signup(local, role);
          // Bind the account's signing key on-chain so every node learns it (see AccountData). This
          // is what lets the account send/receive trustless, account-signed transactions.
          if (pubkey) {
            ctx.ledger.bindAccount(
              created.address as Parameters<typeof ctx.ledger.bindAccount>[0],
              created.role,
              pubkey,
              deriveDid(fromB64u(pubkey)),
            );
          }
          // Every account gets a personal wallet with the faucet grant — same as agents. This is
          // what operators stake from (Ethereum-deposit-contract style) to become an authority.
          if (ctx.config.faucetGrant > 0) {
            ctx.ledger.mint(
              created.address as Parameters<typeof ctx.ledger.mint>[0],
              ctx.config.faucetGrant,
            );
          }
          ctx.bus.emit({
            kind: 'account.created',
            summary: `${created.address} signed up as ${created.role}`,
          });
          // The token is returned exactly once — the client must save it now.
          return reply.code(201).send(created);
        } catch (err) {
          return reply.code(400).send({ error: err instanceof Error ? err.message : String(err) });
        }
      });

      // Bind (or rotate) the signing key for the SIGNED-IN account — how accounts created before
      // keys existed (or a fresh device) enable trustless payments. Authenticated by the caller's
      // token; the key is generated client-side and only its public half is sent.
      http.post('/accounts/key', async (request, reply) => {
        const pubkey = ((request.body ?? {}) as { pubkey?: string }).pubkey?.trim() ?? '';
        if (!pubkey) return reply.code(400).send({ error: 'pubkey is required' });
        // Follower: the caller's TOKEN lives on the authority, not here — this node's account store is
        // a transient chain replica that knows addresses/pubkeys but not tokens. So forward the bind
        // upstream FIRST (like /accounts/me) and let the authority authenticate + write it on-chain;
        // the `account` entry then replicates back. Authenticating locally here would wrongly 401 a
        // perfectly valid token that this follower simply hasn't been told about.
        const upstream = authorityUrl();
        if (upstream) {
          try {
            const res = await fetch(`${upstream}/accounts/key`, {
              method: 'POST',
              headers: passHeaders(request),
              body: JSON.stringify({ pubkey }),
            });
            return reply.code(res.status).send(await res.json().catch(() => ({})));
          } catch {
            return reply.code(502).send({ error: 'could not reach an authority to bind the key' });
          }
        }
        // Authority (or solo): authenticate locally — the token IS held here — then write on-chain.
        const acct = accounts.authenticate(request.headers['x-web3-token'] as string | undefined);
        if (!acct) return reply.code(401).send({ error: 'authentication required' });
        try {
          ctx.ledger.bindAccount(
            acct.address as Parameters<typeof ctx.ledger.bindAccount>[0],
            acct.role,
            pubkey,
            deriveDid(fromB64u(pubkey)),
          );
        } catch {
          return reply.code(400).send({ error: 'pubkey must be base64url-encoded' });
        }
        return reply.send({ bound: true, address: acct.address });
      });

      http.get('/accounts/me', async (request, reply) => {
        // On a follower, accounts live on the authority (this node's store is a transient replica),
        // so resolve login upstream — that's what makes sign-in survive a peer restart.
        const upstream = authorityUrl();
        if (upstream) {
          try {
            const res = await fetch(`${upstream}/accounts/me`, { headers: passHeaders(request) });
            return reply.code(res.status).send(await res.json().catch(() => ({})));
          } catch {
            return reply.code(502).send({ error: 'could not reach an authority to sign in' });
          }
        }
        const acct = accounts.authenticate(
          (request.headers['x-web3-token'] as string | undefined) ??
            (typeof request.headers.authorization === 'string' &&
            request.headers.authorization.startsWith('Bearer ')
              ? request.headers.authorization.slice(7)
              : undefined),
        );
        if (!acct) return reply.code(401).send({ error: 'authentication required' });
        return accounts.view(acct);
      });

      // The signed-in account's OWN earnings — what THEY hold and have received, derived from the
      // ledger for their address. This is the personal view (any role), distinct from the node
      // owner's treasury console under /operator (admin-only). Lets an operator see their wallet +
      // income without ever being shown the node treasury or a Collect button that isn't theirs.
      http.get('/accounts/me/earnings', async (request, reply) => {
        if (!requireAuthed(request, reply, ctx.accounts)) return;
        const acct = currentAccount(request, ctx.accounts);
        if (!acct) return reply.code(401).send({ error: 'authentication required' });
        const address = acct.address as Web3Id;
        let received = 0;
        let sent = 0;
        let txCount = 0;
        for (const entry of ctx.ledger.all() as LedgerEntry<'payment'>[]) {
          if (entry.type !== 'payment') continue;
          const d = entry.data;
          if (d.to === address) {
            received += d.amount;
            txCount++;
          }
          if (d.from === address) {
            sent += d.amount;
            txCount++;
          }
        }
        return {
          address,
          role: acct.role,
          balance: ctx.ledger.balanceOf(address),
          received,
          sent,
          txCount,
        };
      });

      http.get('/accounts', async (request, reply) => {
        // Follower: the account list lives on the authority — forward (admin role checked there).
        const upstream = authorityUrl();
        if (upstream) {
          try {
            const res = await fetch(`${upstream}/accounts`, { headers: passHeaders(request) });
            return reply.code(res.status).send(await res.json().catch(() => ({})));
          } catch {
            return reply.code(502).send({ error: 'could not reach an authority' });
          }
        }
        if (!requireRole(request, reply, accounts, 'admin')) return;
        return { accounts: accounts.list() };
      });
    },
  };
}
