import { useCallback, useEffect, useMemo, useState } from 'react';
import { BUILTIN_CONNECTORS } from './Connectors.js';
import { type CustomConnector, type HostedAgent, NODE_URL, api } from './api.js';

const ADMIN_KEY = 'web3.adminToken';

// Provider → a sensible default model to prefill when the provider changes.
const PROVIDERS: { id: string; label: string; model: string; needsKey: boolean }[] = [
  { id: 'local', label: 'Local (Ollama)', model: 'qwen2.5:7b', needsKey: false },
  { id: 'openai', label: 'OpenAI', model: 'gpt-4o-mini', needsKey: true },
  {
    id: 'openrouter',
    label: 'OpenRouter (many)',
    model: 'anthropic/claude-3.5-sonnet',
    needsKey: true,
  },
  { id: 'anthropic', label: 'Anthropic', model: 'claude-sonnet-5', needsKey: true },
  { id: 'groq', label: 'Groq', model: 'llama-3.3-70b-versatile', needsKey: true },
];

const py = (s: string) => JSON.stringify(s); // JSON strings are valid Python string literals

export function Genesis() {
  const [handle, setHandle] = useState('sage');
  const [name, setName] = useState('Sage');
  const [description, setDescription] = useState('Answers questions with an LLM.');
  const [skillId, setSkillId] = useState('ask');
  const [skillName, setSkillName] = useState('Ask');
  const [skillDesc, setSkillDesc] = useState('Answer a question');
  const [price, setPrice] = useState('3.00');
  const [createdBy, setCreatedBy] = useState('');
  const [provider, setProvider] = useState('local');
  const [model, setModel] = useState('qwen2.5:7b');
  const [system, setSystem] = useState(
    'You are a concise, helpful expert agent on the Web3.0 network.',
  );
  const [copied, setCopied] = useState(false);
  const [apiKey, setApiKey] = useState('');
  const [admin, setAdmin] = useState(() => localStorage.getItem(ADMIN_KEY) ?? '');
  const [launching, setLaunching] = useState(false);
  const [launchMsg, setLaunchMsg] = useState<{ kind: 'ok' | 'err'; text: string } | null>(null);
  const [hosted, setHosted] = useState<HostedAgent[]>([]);
  const [adminRequired, setAdminRequired] = useState(false);
  const [connectors, setConnectors] = useState<string[]>([]);
  const [customConns, setCustomConns] = useState<CustomConnector[]>([]);

  const current = PROVIDERS.find((p) => p.id === provider) ?? PROVIDERS[0];

  // Connectors the operator can assign to the agent: built-in catalogue + any custom ones.
  const connectorOptions = useMemo(
    () => [...BUILTIN_CONNECTORS, ...customConns.map((c) => c.name)],
    [customConns],
  );
  const toggleConnector = (nameStr: string) =>
    setConnectors((cur) =>
      cur.includes(nameStr) ? cur.filter((c) => c !== nameStr) : [...cur, nameStr],
    );

  const refreshHosted = useCallback(async () => {
    try {
      const res = await api.hosted();
      // Genesis manages agents (LLM brains) only — webhook dApps live in Developers / Hosted dApps.
      setHosted(res.agents.filter((a) => a.kind === 'llm'));
      setAdminRequired(res.adminRequired);
    } catch {
      /* node may be offline */
    }
  }, []);

  useEffect(() => {
    refreshHosted();
    const t = setInterval(refreshHosted, 5000);
    return () => clearInterval(t);
  }, [refreshHosted]);

  useEffect(() => {
    api
      .connectors()
      .then((r) => setCustomConns(r.connectors))
      .catch(() => setCustomConns([]));
  }, []);

  const rememberAdmin = (value: string) => {
    setAdmin(value);
    localStorage.setItem(ADMIN_KEY, value);
  };

  async function launch() {
    setLaunching(true);
    setLaunchMsg(null);
    try {
      const minorUnits = Math.max(0, Math.round(Number.parseFloat(price || '0') * 100));
      const agent = await api.hostedLaunch(
        {
          handle,
          name,
          description,
          skillId,
          skillName,
          skillDesc,
          price: minorUnits,
          provider,
          model,
          apiKey: apiKey || undefined,
          system,
          createdBy: createdBy.trim() || undefined,
          connectors,
        },
        admin,
      );
      if (createdBy.trim()) localStorage.setItem('web3.creatorName', createdBy.trim());
      setLaunchMsg({ kind: 'ok', text: `Launched ${agent.web3Id} — live on the node.` });
      setApiKey('');
      refreshHosted();
    } catch (err) {
      setLaunchMsg({ kind: 'err', text: err instanceof Error ? err.message : String(err) });
    } finally {
      setLaunching(false);
    }
  }

  async function stopHosted(h: string) {
    try {
      await api.hostedStop(h, admin);
      refreshHosted();
    } catch (err) {
      setLaunchMsg({ kind: 'err', text: err instanceof Error ? err.message : String(err) });
    }
  }

  const script = useMemo(() => {
    const minorUnits = Math.max(0, Math.round(Number.parseFloat(price || '0') * 100));
    return `"""Web3.0 agent generated by Genesis. Bring your own key — it stays on your machine.

Run it:
  ${current.needsKey ? '1. Put your provider key in .env:  LLM_API_KEY=your-key\\n  ' : ''}${current.needsKey ? '2' : '1'}. python ${handle}_agent.py

The agent registers on your node, connects, and starts earning ${price} aETH per task.
"""

import time
from web3_sdk import Agent, LLM, LLMError, load_env

load_env()  # reads LLM_API_KEY / LLM_* from your .env (never sent to the network)

agent = Agent(
    ${py(handle)},
    name=${py(name)},
    description=${py(description)},
    base_url=${py(NODE_URL)},
    skills=[{"id": ${py(skillId)}, "name": ${py(skillName)}, "description": ${py(skillDesc)}, "tags": []}],
    pricing={"perTask": ${minorUnits}, "currency": "aETH"},
)

# The brain — your chosen provider and model. The key comes from LLM_API_KEY in .env.
brain = LLM.provider(${py(provider)}, model=${py(model)}, system=${py(system)})

agent.register()

def on_task(a, message):
    body = message["body"]
    payload = body.get("input", {})
    prompt = payload.get("prompt") or payload.get("question") or str(payload)
    try:
        answer = brain.chat(prompt)
    except LLMError as exc:
        a.reply_result(message["from"], body["taskId"], {"error": str(exc)}, state="failed")
        return
    a.reply_result(message["from"], body["taskId"], {"answer": answer})

agent.on_task(on_task)
agent.connect()
print(f"{agent.web3_id} is live on Web3.0 (brain: {brain.provider_name}/{brain.model}). Ctrl+C to stop.")
while True:
    time.sleep(1)
`;
  }, [
    handle,
    name,
    description,
    skillId,
    skillName,
    skillDesc,
    price,
    provider,
    model,
    system,
    current,
  ]);

  function onProviderChange(id: string) {
    setProvider(id);
    const preset = PROVIDERS.find((p) => p.id === id);
    if (preset) setModel(preset.model);
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(script);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  }

  return (
    <>
      <div className="page-head">
        <h1>Genesis</h1>
        <span className="muted">spin up an agent — pick a brain, keep your own key</span>
      </div>

      <div className="card" style={{ marginBottom: 18 }}>
        <div className="section-title">Configure your agent</div>
        <div className="form-grid">
          <div className="field">
            <label htmlFor="g-handle">Web3.0 ID</label>
            <input id="g-handle" value={handle} onChange={(e) => setHandle(e.target.value)} />
            <span className="hint">{handle || '…'}@web3.0</span>
          </div>
          <div className="field">
            <label htmlFor="g-name">Display name</label>
            <input id="g-name" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="field wide">
            <label htmlFor="g-desc">Description</label>
            <input
              id="g-desc"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>

          <div className="field">
            <label htmlFor="g-provider">LLM provider (brain)</label>
            <select
              id="g-provider"
              value={provider}
              onChange={(e) => onProviderChange(e.target.value)}
            >
              {PROVIDERS.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.label}
                </option>
              ))}
            </select>
            <span className="hint">
              {current.needsKey
                ? 'needs your API key in .env (LLM_API_KEY)'
                : 'runs locally, no key'}
            </span>
          </div>
          <div className="field">
            <label htmlFor="g-model">Model</label>
            <input id="g-model" value={model} onChange={(e) => setModel(e.target.value)} />
          </div>

          {current.needsKey && (
            <div className="field wide">
              <label htmlFor="g-key">{current.label} API key (for launching on the node)</label>
              <input
                id="g-key"
                type="password"
                value={apiKey}
                onChange={(e) => setApiKey(e.target.value)}
                placeholder="stored server-side, only used to run this agent"
              />
              <span className="hint">
                Only needed for the “Launch on node” button. The downloadable script reads its key
                from your own <code>.env</code> instead.
              </span>
            </div>
          )}

          <div className="field">
            <label htmlFor="g-skill-id">Skill id</label>
            <input id="g-skill-id" value={skillId} onChange={(e) => setSkillId(e.target.value)} />
          </div>
          <div className="field">
            <label htmlFor="g-price">Price per task (aETH)</label>
            <input id="g-price" value={price} onChange={(e) => setPrice(e.target.value)} />
          </div>
          <div className="field">
            <label htmlFor="g-creator">Created by (your name / team)</label>
            <input
              id="g-creator"
              value={createdBy}
              onChange={(e) => setCreatedBy(e.target.value)}
              placeholder="e.g. Dr. Sanjay Anbu"
            />
          </div>
          <div className="field">
            <label htmlFor="g-skill-name">Skill name</label>
            <input
              id="g-skill-name"
              value={skillName}
              onChange={(e) => setSkillName(e.target.value)}
            />
          </div>
          <div className="field">
            <label htmlFor="g-skill-desc">Skill description</label>
            <input
              id="g-skill-desc"
              value={skillDesc}
              onChange={(e) => setSkillDesc(e.target.value)}
            />
          </div>
          <div className="field wide">
            <label htmlFor="g-system">System prompt (the agent's persona)</label>
            <textarea id="g-system" value={system} onChange={(e) => setSystem(e.target.value)} />
          </div>
          <div className="field wide">
            <span className="field-lbl">Connectors this agent uses</span>
            <div className="chip-pick">
              {connectorOptions.map((c) => (
                <button
                  type="button"
                  key={c}
                  className={`chip-toggle ${connectors.includes(c) ? 'on' : ''}`}
                  onClick={() => toggleConnector(c)}
                >
                  {c}
                </button>
              ))}
            </div>
            <span className="hint">
              {connectors.length} selected — click to add/remove. Add more in the Connectors tab.
            </span>
          </div>
        </div>
      </div>

      <div className="card" style={{ marginBottom: 18 }}>
        <div className="section-title">Launch on the node (one click — no VPS)</div>
        <p className="muted" style={{ margin: '2px 0 12px' }}>
          Run this agent inside the node itself. It registers, hosts its LLM brain, and starts
          earning immediately — nothing to install, no separate process.
        </p>
        {adminRequired && (
          <div className="field wide">
            <label htmlFor="g-admin">Admin token</label>
            <input
              id="g-admin"
              type="password"
              value={admin}
              onChange={(e) => rememberAdmin(e.target.value)}
              placeholder="required to launch on this node"
            />
          </div>
        )}
        <div className="gen-actions">
          <button type="button" className="btn act" disabled={launching} onClick={launch}>
            {launching ? 'Launching…' : 'Launch on node'}
          </button>
        </div>
        {launchMsg && (
          <div className={`note ${launchMsg.kind === 'err' ? 'note-err' : 'note-ok'}`}>
            {launchMsg.text}
          </div>
        )}
        {hosted.length > 0 && (
          <ul className="kv-list" style={{ marginTop: 14 }}>
            {hosted.map((h) => (
              <li key={h.web3Id}>
                <span>
                  <code>{h.web3Id}</code> · {h.provider}/{h.model} ·{' '}
                  <span className={`chip ${h.running ? 'allow' : 'deny'}`}>
                    {h.running ? 'running' : 'stopped'}
                  </span>
                  {h.connectors && h.connectors.length > 0 && (
                    <span className="muted" style={{ marginLeft: 6, fontSize: 'var(--fs-sm)' }}>
                      · connectors: {h.connectors.join(', ')}
                    </span>
                  )}
                </span>
                {h.running && (
                  <button
                    type="button"
                    className="btn ghost btn-sm"
                    onClick={() => stopHosted(h.handle)}
                  >
                    Stop
                  </button>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>

      <div className="card">
        <div className="section-title">Or download the script</div>
        <div className="gen-actions">
          <button type="button" className="btn btn-sm" onClick={copy}>
            Copy script
          </button>
          {copied && <span className="copied">copied ✓</span>}
        </div>
        <pre>
          <code>{script}</code>
        </pre>
        <div className="section-title" style={{ marginTop: 18 }}>
          Launch it
        </div>
        <ol className="steps">
          <li>
            Save the script as <code>{handle}_agent.py</code> in the repo folder.
          </li>
          {current.needsKey && (
            <li>
              Put your {current.label} key in <code>.env</code>: <code>LLM_API_KEY=your-key</code>
            </li>
          )}
          <li>
            Activate the venv and run it: <code>python {handle}_agent.py</code>
          </li>
          <li>Your agent registers, connects, and appears live in Agents & Live traffic. 🎉</li>
        </ol>
        <p className="hint" style={{ marginTop: 10 }}>
          Your provider key stays on your machine — it is never sent to the Web3.0 node or the
          network.
        </p>
      </div>
    </>
  );
}
