import { useMemo, useState } from 'react';
import { NODE_URL } from './api.js';

// Provider → a sensible default model to prefill when the provider changes.
const PROVIDERS: { id: string; label: string; model: string; needsKey: boolean }[] = [
  { id: 'local', label: 'Local (Ollama)', model: 'qwen2.5:7b', needsKey: false },
  { id: 'openai', label: 'OpenAI', model: 'gpt-4o-mini', needsKey: true },
  {
    id: 'openrouter',
    label: 'OpenRouter (many)',
    model: 'anthropic/claude-3.5-sonnet',
    needsKey: true,
  },
  { id: 'anthropic', label: 'Anthropic', model: 'claude-sonnet-5', needsKey: true },
  { id: 'groq', label: 'Groq', model: 'llama-3.3-70b-versatile', needsKey: true },
];

const py = (s: string) => JSON.stringify(s); // JSON strings are valid Python string literals

export function Genesis() {
  const [handle, setHandle] = useState('sage');
  const [name, setName] = useState('Sage');
  const [description, setDescription] = useState('Answers questions with an LLM.');
  const [skillId, setSkillId] = useState('ask');
  const [skillName, setSkillName] = useState('Ask');
  const [skillDesc, setSkillDesc] = useState('Answer a question');
  const [price, setPrice] = useState('3.00');
  const [provider, setProvider] = useState('local');
  const [model, setModel] = useState('qwen2.5:7b');
  const [system, setSystem] = useState(
    'You are a concise, helpful expert agent on the ACP network.',
  );
  const [copied, setCopied] = useState(false);

  const current = PROVIDERS.find((p) => p.id === provider) ?? PROVIDERS[0];

  const script = useMemo(() => {
    const minorUnits = Math.max(0, Math.round(Number.parseFloat(price || '0') * 100));
    return `"""ACP agent generated by Genesis. Bring your own key — it stays on your machine.

Run it:
  ${current.needsKey ? '1. Put your provider key in .env:  LLM_API_KEY=your-key\\n  ' : ''}${current.needsKey ? '2' : '1'}. python ${handle}_agent.py

The agent registers on your node, connects, and starts earning ${price} aUSD per task.
"""

import time
from acp_sdk import Agent, LLM, LLMError, load_env

load_env()  # reads LLM_API_KEY / LLM_* from your .env (never sent to the network)

agent = Agent(
    ${py(handle)},
    name=${py(name)},
    description=${py(description)},
    base_url=${py(NODE_URL)},
    skills=[{"id": ${py(skillId)}, "name": ${py(skillName)}, "description": ${py(skillDesc)}, "tags": []}],
    pricing={"perTask": ${minorUnits}, "currency": "aUSD"},
)

# The brain — your chosen provider and model. The key comes from LLM_API_KEY in .env.
brain = LLM.provider(${py(provider)}, model=${py(model)}, system=${py(system)})

agent.register()

def on_task(a, message):
    body = message["body"]
    payload = body.get("input", {})
    prompt = payload.get("prompt") or payload.get("question") or str(payload)
    try:
        answer = brain.chat(prompt)
    except LLMError as exc:
        a.reply_result(message["from"], body["taskId"], {"error": str(exc)}, state="failed")
        return
    a.reply_result(message["from"], body["taskId"], {"answer": answer})

agent.on_task(on_task)
agent.connect()
print(f"{agent.web3_id} is live on ACP (brain: {brain.provider_name}/{brain.model}). Ctrl+C to stop.")
while True:
    time.sleep(1)
`;
  }, [
    handle,
    name,
    description,
    skillId,
    skillName,
    skillDesc,
    price,
    provider,
    model,
    system,
    current,
  ]);

  function onProviderChange(id: string) {
    setProvider(id);
    const preset = PROVIDERS.find((p) => p.id === id);
    if (preset) setModel(preset.model);
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(script);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  }

  return (
    <>
      <div className="page-head">
        <h1>Genesis</h1>
        <span className="muted">spin up an agent — pick a brain, keep your own key</span>
      </div>

      <div className="card" style={{ marginBottom: 18 }}>
        <div className="section-title">Configure your agent</div>
        <div className="form-grid">
          <div className="field">
            <label htmlFor="g-handle">Web3.0 ID</label>
            <input id="g-handle" value={handle} onChange={(e) => setHandle(e.target.value)} />
            <span className="hint">{handle || '…'}@web3.0</span>
          </div>
          <div className="field">
            <label htmlFor="g-name">Display name</label>
            <input id="g-name" value={name} onChange={(e) => setName(e.target.value)} />
          </div>
          <div className="field wide">
            <label htmlFor="g-desc">Description</label>
            <input
              id="g-desc"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>

          <div className="field">
            <label htmlFor="g-provider">LLM provider (brain)</label>
            <select
              id="g-provider"
              value={provider}
              onChange={(e) => onProviderChange(e.target.value)}
            >
              {PROVIDERS.map((p) => (
                <option key={p.id} value={p.id}>
                  {p.label}
                </option>
              ))}
            </select>
            <span className="hint">
              {current.needsKey
                ? 'needs your API key in .env (LLM_API_KEY)'
                : 'runs locally, no key'}
            </span>
          </div>
          <div className="field">
            <label htmlFor="g-model">Model</label>
            <input id="g-model" value={model} onChange={(e) => setModel(e.target.value)} />
          </div>

          <div className="field">
            <label htmlFor="g-skill-id">Skill id</label>
            <input id="g-skill-id" value={skillId} onChange={(e) => setSkillId(e.target.value)} />
          </div>
          <div className="field">
            <label htmlFor="g-price">Price per task (aUSD)</label>
            <input id="g-price" value={price} onChange={(e) => setPrice(e.target.value)} />
          </div>
          <div className="field">
            <label htmlFor="g-skill-name">Skill name</label>
            <input
              id="g-skill-name"
              value={skillName}
              onChange={(e) => setSkillName(e.target.value)}
            />
          </div>
          <div className="field">
            <label htmlFor="g-skill-desc">Skill description</label>
            <input
              id="g-skill-desc"
              value={skillDesc}
              onChange={(e) => setSkillDesc(e.target.value)}
            />
          </div>
          <div className="field wide">
            <label htmlFor="g-system">System prompt (the agent's persona)</label>
            <textarea id="g-system" value={system} onChange={(e) => setSystem(e.target.value)} />
          </div>
        </div>
      </div>

      <div className="card">
        <div className="section-title">Your agent</div>
        <div className="gen-actions">
          <button type="button" className="btn btn-sm" onClick={copy}>
            Copy script
          </button>
          {copied && <span className="copied">copied ✓</span>}
        </div>
        <pre>
          <code>{script}</code>
        </pre>
        <div className="section-title" style={{ marginTop: 18 }}>
          Launch it
        </div>
        <ol className="steps">
          <li>
            Save the script as <code>{handle}_agent.py</code> in the repo folder.
          </li>
          {current.needsKey && (
            <li>
              Put your {current.label} key in <code>.env</code>: <code>LLM_API_KEY=your-key</code>
            </li>
          )}
          <li>
            Activate the venv and run it: <code>python {handle}_agent.py</code>
          </li>
          <li>Your agent registers, connects, and appears live in Agents & Live traffic. 🎉</li>
        </ol>
        <p className="hint" style={{ marginTop: 10 }}>
          Your provider key stays on your machine (read from <code>.env</code>) — it is never sent
          to the ACP node or the network.
        </p>
      </div>
    </>
  );
}
